# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Mips_Assembler.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(837, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(200, 100))
        self.tabWidget.setObjectName("tabWidget")
        self.Edit = QtWidgets.QWidget()
        self.Edit.setObjectName("Edit")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Edit)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.Edit)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_4.addWidget(self.textEdit)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.Edit, "")
        self.Text_Segement = QtWidgets.QWidget()
        self.Text_Segement.setObjectName("Text_Segement")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Text_Segement)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Text_Segement)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(270)
        self.verticalLayout_4.addWidget(self.tableWidget_2)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.Text_Segement, "")
        self.Data_Segment = QtWidgets.QWidget()
        self.Data_Segment.setObjectName("Data_Segment")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Data_Segment)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Data_Segment)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_3.setAutoFillBackground(True)
        self.tableWidget_3.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_3.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_3.setRowCount(8192)
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setObjectName("tableWidget_3")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 1, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.tableWidget_3)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.Data_Segment, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_5)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_6.addWidget(self.textBrowser)
        self.horizontalLayout_5.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(33)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(24, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(25, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(26, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(27, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(28, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(29, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(30, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(31, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(32, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(118)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.horizontalLayout.addWidget(self.groupBox, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 837, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/[FreeCoursesOnline.Me] [Packt] Python GUI Programming Recipes using PyQt5 [FCO]/Exercise Files/Codes/Code/Section1/icons/new_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/[FreeCoursesOnline.Me] [Packt] Python GUI Programming Recipes using PyQt5 [FCO]/Exercise Files/Codes/Code/Section1/icons/exit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName("actionExit")
        self.actionAssemble = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("play-button-png-transparent.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAssemble.setIcon(icon2)
        self.actionAssemble.setObjectName("actionAssemble")
        self.actionvvv = QtWidgets.QAction(MainWindow)
        self.actionvvv.setObjectName("actionvvv")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuRun.addAction(self.actionAssemble)
        self.menuRun.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.pushButton_2.clicked.connect(MainWindow.close)
        self.actionExit.triggered.connect(MainWindow.close)
        self.actionNew.triggered.connect(self.textEdit.clear)
        self.actionNew.triggered.connect(self.tableWidget_2.clearContents)
        self.actionNew.triggered.connect(self.tableWidget_3.clearContents)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MIPS_Assembler"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Assembly code"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Edit), _translate("MainWindow", "Edit"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Text Segment"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Instruction"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Machine Code"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Text_Segement), _translate("MainWindow", "Text_Segement"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Data Segment"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Adress"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Data"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Data_Segment), _translate("MainWindow", "Data_Segment"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Automated_Testing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Automated_Testing"))
        self.groupBox.setTitle(_translate("MainWindow", "Registers"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "$zero"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "$at"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "$v0"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "$v1"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "$a0"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "$a1"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "$a2"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "$a3"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "$t0"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "$t1"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("MainWindow", "$t2"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("MainWindow", "$t3"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("MainWindow", "$t4"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("MainWindow", "$t5"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("MainWindow", "$t6"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("MainWindow", "$t7"))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("MainWindow", "$s0"))
        item = self.tableWidget.item(17, 0)
        item.setText(_translate("MainWindow", "$s1"))
        item = self.tableWidget.item(18, 0)
        item.setText(_translate("MainWindow", "$s2"))
        item = self.tableWidget.item(19, 0)
        item.setText(_translate("MainWindow", "$s3"))
        item = self.tableWidget.item(20, 0)
        item.setText(_translate("MainWindow", "$s4"))
        item = self.tableWidget.item(21, 0)
        item.setText(_translate("MainWindow", "$s5"))
        item = self.tableWidget.item(22, 0)
        item.setText(_translate("MainWindow", "$s6"))
        item = self.tableWidget.item(23, 0)
        item.setText(_translate("MainWindow", "$s7"))
        item = self.tableWidget.item(24, 0)
        item.setText(_translate("MainWindow", "$t8"))
        item = self.tableWidget.item(25, 0)
        item.setText(_translate("MainWindow", "$t9"))
        item = self.tableWidget.item(26, 0)
        item.setText(_translate("MainWindow", "$k0"))
        item = self.tableWidget.item(27, 0)
        item.setText(_translate("MainWindow", "$k1"))
        item = self.tableWidget.item(28, 0)
        item.setText(_translate("MainWindow", "$gp"))
        item = self.tableWidget.item(29, 0)
        item.setText(_translate("MainWindow", "$sp"))
        item = self.tableWidget.item(30, 0)
        item.setText(_translate("MainWindow", "$fp"))
        item = self.tableWidget.item(31, 0)
        item.setText(_translate("MainWindow", "$ra"))
        item = self.tableWidget.item(32, 0)
        item.setText(_translate("MainWindow", "pc"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Assemble"))
        self.pushButton_3.setText(_translate("MainWindow", " Run Automated Testing "))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAssemble.setText(_translate("MainWindow", "Assemble"))
        self.actionvvv.setText(_translate("MainWindow", "vvv"))
